/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachClientAcquisitionRouteImport } from './routes/coach-client-acquisition'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuditsTokenRouteImport } from './routes/audits.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachClientAcquisitionRoute = CoachClientAcquisitionRouteImport.update({
  id: '/coach-client-acquisition',
  path: '/coach-client-acquisition',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsTokenRoute = AuditsTokenRouteImport.update({
  id: '/audits/$token',
  path: '/audits/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach-client-acquisition': typeof CoachClientAcquisitionRoute
  '/onboarding': typeof OnboardingRoute
  '/audits/$token': typeof AuditsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach-client-acquisition': typeof CoachClientAcquisitionRoute
  '/onboarding': typeof OnboardingRoute
  '/audits/$token': typeof AuditsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach-client-acquisition': typeof CoachClientAcquisitionRoute
  '/onboarding': typeof OnboardingRoute
  '/audits/$token': typeof AuditsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/coach-client-acquisition' | '/onboarding' | '/audits/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coach-client-acquisition' | '/onboarding' | '/audits/$token'
  id:
    | '__root__'
    | '/'
    | '/coach-client-acquisition'
    | '/onboarding'
    | '/audits/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachClientAcquisitionRoute: typeof CoachClientAcquisitionRoute
  OnboardingRoute: typeof OnboardingRoute
  AuditsTokenRoute: typeof AuditsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-client-acquisition': {
      id: '/coach-client-acquisition'
      path: '/coach-client-acquisition'
      fullPath: '/coach-client-acquisition'
      preLoaderRoute: typeof CoachClientAcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$token': {
      id: '/audits/$token'
      path: '/audits/$token'
      fullPath: '/audits/$token'
      preLoaderRoute: typeof AuditsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachClientAcquisitionRoute: CoachClientAcquisitionRoute,
  OnboardingRoute: OnboardingRoute,
  AuditsTokenRoute: AuditsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
